"""RFdiffusion adapter for ProtClaw.

Wraps the RFdiffusion CLI for protein backbone generation via diffusion.
Input: contig specification, number of designs, noise parameters.
Output: PDB files of generated backbones in output_dir.
"""

from __future__ import annotations

import glob
import os
import shutil
import subprocess
from typing import Any

from common.adapter_protocol import BaseTool, ToolResult


class RFdiffusionAdapter(BaseTool):
    """Adapter for RFdiffusion protein backbone generation."""

    tool_name = "rfdiffusion"
    tool_version = "1.1.0"

    # Default parameter values
    DEFAULTS: dict[str, Any] = {
        "num_designs": 1,
        "noise_scale": 1.0,
        "partial_T": None,
        "model_checkpoint": None,
    }

    def validate_input(self, params: dict[str, Any]) -> dict[str, Any]:
        """Validate RFdiffusion input parameters.

        Required:
            contigs: str - Contig specification (e.g., "100-100" for 100-residue chain)

        Optional:
            num_designs: int - Number of designs to generate (default: 1)
            noise_scale: float - Noise scale for diffusion (default: 1.0)
            partial_T: int | None - Partial diffusion timesteps
            model_checkpoint: str | None - Path to model weights
        """
        validated = dict(self.DEFAULTS)
        validated.update(params)

        # Required: contigs
        if "contigs" not in validated or not validated["contigs"]:
            raise ValueError("'contigs' is required (e.g., '100-100' for 100-residue chain)")

        contigs = str(validated["contigs"])
        validated["contigs"] = contigs

        # Validate num_designs
        num_designs = int(validated["num_designs"])
        if num_designs < 1 or num_designs > 1000:
            raise ValueError(f"num_designs must be between 1 and 1000, got {num_designs}")
        validated["num_designs"] = num_designs

        # Validate noise_scale
        noise_scale = float(validated["noise_scale"])
        if noise_scale < 0.0:
            raise ValueError(f"noise_scale must be non-negative, got {noise_scale}")
        validated["noise_scale"] = noise_scale

        # Validate partial_T if provided
        if validated["partial_T"] is not None:
            partial_t = int(validated["partial_T"])
            if partial_t < 1:
                raise ValueError(f"partial_T must be positive, got {partial_t}")
            validated["partial_T"] = partial_t

        return validated

    def execute(self, params: dict[str, Any], input_dir: str, output_dir: str) -> ToolResult:
        """Execute RFdiffusion backbone generation.

        Calls the RFdiffusion inference script and collects generated PDB files.
        """
        contigs = params["contigs"]
        num_designs = params["num_designs"]
        noise_scale = params["noise_scale"]

        # TODO: Replace with actual RFdiffusion model call
        # In production, this would call:
        #   python /opt/rfdiffusion/run_inference.py \
        #     inference.output_prefix={output_dir}/design \
        #     'contigmap.contigs=[{contigs}]' \
        #     inference.num_designs={num_designs} \
        #     denoiser.noise_scale_ca={noise_scale} \
        #     denoiser.noise_scale_frame={noise_scale}
        #
        # For now, generate stub PDB files as placeholders.

        output_files = []
        for i in range(num_designs):
            pdb_filename = f"design_{i:04d}.pdb"
            pdb_path = os.path.join(output_dir, pdb_filename)

            # Write a minimal valid PDB stub
            with open(pdb_path, "w") as f:
                f.write(f"REMARK   Generated by RFdiffusion stub (design {i})\n")
                f.write(f"REMARK   Contigs: {contigs}\n")
                f.write(f"REMARK   Noise scale: {noise_scale}\n")
                # Write a placeholder ATOM record
                f.write(
                    "ATOM      1  CA  ALA A   1       0.000   0.000   0.000  1.00  0.00"
                    "           C\n"
                )
                f.write("END\n")

            output_files.append(pdb_path)

        return self.build_result(
            status="success",
            output_files=output_files,
            metrics={
                "num_designs_generated": len(output_files),
                "contigs": contigs,
                "noise_scale": noise_scale,
            },
        )


def create_adapter() -> RFdiffusionAdapter:
    """Factory function to create adapter instance."""
    return RFdiffusionAdapter()
